//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NRemedy
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    using NRemedy;
    using BMC.ARSystem;
    using ARNative;

    [NRemedy.ARFormAttribute(FormName = "NRemedy_Test_Regular_Form")]
    public class NRemedy_Test_Regular_Form : ARBaseForm
    {
        private String _RequestID;
        private Status_Enum _Status;
        private String _CharacterField;
        private Int32? _IntegerField;
        private DateTime? _DateTimeField;
        private DateValue _DateField;
        private TimeOfDayValue _TimeField;
        private Double? _RealNumberField;
        private Decimal? _DecimalNumberField;
        private ARAttachment _Attachment;
        private Nullable<Radio_Button_Field_Enum> _Radio_Button_Field;
        [NRemedy.ARFieldAttribute(DatabaseID = 1u, DatabaseName = "Request ID", DataType = ARType.CharacterField, BinderAccess = ModelBinderAccessLevel.OnlyBind)]
        [NRemedy.AREntryKey]
        public String RequestID
        {
            get
            {
                return this._RequestID;
            }
            set
            {
                this._RequestID = value;
                this.OnPropertyChanged("RequestID");
            }
        }
        [NRemedy.ARFieldAttribute(DatabaseID = 7u, DatabaseName = "Status", DataType = ARType.SelectionField)]
        public Status_Enum Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this._Status = value;
                this.OnPropertyChanged("Status");
            }
        }
        [NRemedy.ARFieldAttribute(DatabaseID = 20000001u, DatabaseName = "Character Field", DataType = ARType.CharacterField)]
        public String CharacterField
        {
            get
            {
                return this._CharacterField;
            }
            set
            {
                this._CharacterField = value;
                this.OnPropertyChanged("CharacterField");
            }
        }
        [NRemedy.ARFieldAttribute(DatabaseID = 20000002u, DatabaseName = "Integer Field", DataType = ARType.IntegerField)]
        public Int32? IntegerField
        {
            get
            {
                return this._IntegerField;
            }
            set
            {
                this._IntegerField = value;
                this.OnPropertyChanged("IntegerField");
            }
        }
        [NRemedy.ARFieldAttribute(DatabaseID = 20000003u, DatabaseName = "Date/Time Field", DataType = ARType.DateTimeField)]
        public DateTime? DateTimeField
        {
            get
            {
                return this._DateTimeField;
            }
            set
            {
                this._DateTimeField = value;
                this.OnPropertyChanged("DateTimeField");
            }
        }
        [NRemedy.ARFieldAttribute(DatabaseID = 20000004u, DatabaseName = "Date Field", DataType = ARType.DateOnlyField)]
        public DateValue DateField
        {
            get
            {
                return this._DateField;
            }
            set
            {
                this._DateField = value;
                this.OnPropertyChanged("DateField");
            }
        }
        [NRemedy.ARFieldAttribute(DatabaseID = 2000005u, DatabaseName = "Time Field", DataType = ARType.TimeOnlyField)]
        public TimeOfDayValue TimeField
        {
            get
            {
                return this._TimeField;
            }
            set
            {
                this._TimeField = value;
                this.OnPropertyChanged("TimeField");
            }
        }
        [NRemedy.ARFieldAttribute(DatabaseID = 20000006u, DatabaseName = "Real Number Field", DataType = ARType.RealField)]
        public Double? RealNumberField
        {
            get
            {
                return this._RealNumberField;
            }
            set
            {
                this._RealNumberField = value;
                this.OnPropertyChanged("RealNumberField");
            }
        }
        [NRemedy.ARFieldAttribute(DatabaseID = 20000007u, DatabaseName = "Decimal Number Field", DataType = ARType.DecimalField)]
        public Decimal? DecimalNumberField
        {
            get
            {
                return this._DecimalNumberField;
            }
            set
            {
                this._DecimalNumberField = value;
                this.OnPropertyChanged("DecimalNumberField");
            }
        }

        [NRemedy.ARFieldAttribute(DatabaseID = 20000011u, DatabaseName = "Attachment", DataType = ARType.AttachmentField)]
        public ARAttachment Attachment
        {
            get
            {
                return this._Attachment;
            }
            set
            {
                this._Attachment = value;
                this.OnPropertyChanged("Attachment");
            }
        }

        [NRemedy.ARFieldAttribute(DatabaseID = 20000009u, DatabaseName = "Radio Button Field", DataType = ARType.SelectionField)]
        public Nullable<Radio_Button_Field_Enum> Radio_Button_Field
        {
            get
            {
                return this._Radio_Button_Field;
            }
            set
            {
                this._Radio_Button_Field = value;
                this.OnPropertyChanged("Radio_Button_Field");
            }
        }

        public enum Status_Enum
        {
            New = 0,
            Assigned = 1,
            Fixed = 2,
            Rejected = 3,
            Closed = 4,
        }

        public enum Radio_Button_Field_Enum
        {
            First = 0,
            Second = 1
        }
    }
}
