//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NRemedy
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    using NRemedy;

    [NRemedy.ARFormAttribute(FormName = "NRemedy_Test_Join_Form")]
    public class NRemedy_Test_Join_Form : ARBaseForm
    {
        private String _RequestID;
        private String _CharacterField;
        private String _ShortDescription;
        private String _ShortDescription2;
        private String _CharacterField2;
        private String _GUID;
        [NRemedy.ARFieldAttribute(DatabaseID = 1u, DatabaseName = "Request ID", DataType = ARType.CharacterField)]
        public String RequestID
        {
            get
            {
                return this._RequestID;
            }
            set
            {
                this._RequestID = value;
                this.OnPropertyChanged("RequestID");
            }
        }
        [NRemedy.ARFieldAttribute(DatabaseID = 20000001u, DatabaseName = "Character Field", DataType = ARType.CharacterField)]
        public String CharacterField
        {
            get
            {
                return this._CharacterField;
            }
            set
            {
                this._CharacterField = value;
                this.OnPropertyChanged("CharacterField");
            }
        }
        [NRemedy.ARFieldAttribute(DatabaseID = 8u, DatabaseName = "Short Description", DataType = ARType.CharacterField)]
        public String ShortDescription
        {
            get
            {
                return this._ShortDescription;
            }
            set
            {
                this._ShortDescription = value;
                this.OnPropertyChanged("ShortDescription");
            }
        }
        [NRemedy.ARFieldAttribute(DatabaseID = 536870913u, DatabaseName = "Short Description2", DataType = ARType.CharacterField)]
        public String ShortDescription2
        {
            get
            {
                return this._ShortDescription2;
            }
            set
            {
                this._ShortDescription2 = value;
                this.OnPropertyChanged("ShortDescription2");
            }
        }
        [NRemedy.ARFieldAttribute(DatabaseID = 21000001u, DatabaseName = "Character Field2", DataType = ARType.CharacterField)]
        public String CharacterField2
        {
            get
            {
                return this._CharacterField2;
            }
            set
            {
                this._CharacterField2 = value;
                this.OnPropertyChanged("CharacterField2");
            }
        }
        [NRemedy.ARFieldAttribute(DatabaseID = 536870915u, DatabaseName = "GUID", DataType = ARType.CharacterField)]
        public String GUID
        {
            get
            {
                return this._GUID;
            }
            set
            {
                this._GUID = value;
                this.OnPropertyChanged("GUID");
            }
        }
    }
}
